name: "Check builds working"

on: 
  pull_request:
  push:
    branches: 
      - master

jobs: 
  check_client_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install volta
        uses: volta-cli/action@v4

      - run: yarn workspaces focus client
      - run: yarn workspace client build

  check_server_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install volta
        uses: volta-cli/action@v4
      
      - run: yarn workspaces focus server
      - run: yarn workspace server build