name: Fly Deploy Staging

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_STAGING_API_TOKEN }}

jobs:
  deploy-api:
    name: Deploy Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set --config fly.staging.toml "GOOGLE_SERVICE_ACCOUNT_JSON=$(echo ${{ secrets.STAGING_SERVER_SERVICE_ACCOUNT }} | base64 --decode)" STRIPE_API_SECRET=${{ secrets.STAGING_SERVER_STRIPE_API_SECRET }} STRIPE_API_KEY=${{ secrets.STAGING_SERVER_STRIPE_API_KEY }}
      - run: flyctl secrets deploy --config fly.staging.toml
      - run: flyctl deploy --remote-only --config fly.staging.toml
