name: Fly Deploy Production

on: [workflow_dispatch]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_PRODUCTION_API_TOKEN }}

jobs:
  deploy-api:
    name: Deploy Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set --config fly.production.toml "GOOGLE_SERVICE_ACCOUNT_JSON=$(echo ${{ secrets.PROD_SERVER_SERVICE_ACCOUNT }} | base64 --decode)" STRIPE_API_SECRET=${{ secrets.PROD_SERVER_STRIPE_API_SECRET }} STRIPE_API_KEY=${{ secrets.PROD_SERVER_STRIPE_API_KEY  }}
      - run: flyctl secrets deploy --config fly.production.toml
      - run: flyctl deploy --remote-only --config fly.production.toml