name: Fly Deploy Staging

on:
  pull_request:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_STAGING_API_TOKEN }}

jobs:
  # deploy-web:
  #   name: Deploy Web
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - run: flyctl deploy --remote-only --config fly.staging.toml
  #       working-directory: ./web
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_WEB_STAGING_API_TOKEN }}

  deploy-api:
    name: Deploy Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets --config fly.staging.toml GOOGLE_SERVICE_ACCOUNT_JSON=$(echo ${{ secrets.STAGING_SERVER_SERVICE_ACCOUNT }} | base64 --decode) STRIPE_API_SECRET=${{ secrets.STAGING_SERVER_STRIPE_API_SECRET }} STRIPE_API_KEY=${{ secrets.STAGING_SERVER_STRIPE_API_KEY }}
      - run: flyctl secrets deploy
      - run: flyctl deploy --remote-only --config fly.staging.toml
