name: Deploy Production Build of Client for UASC 

on: [workflow_dispatch]

env:
  VITE_FIREBASE_API_KEY: ${{secrets.PROD_FIREBASE_API_KEY}}
  VITE_FIREBASE_AUTH_DOMAIN: ${{secrets.PROD_FIREBASE_AUTH_DOMAIN}}
  VITE_FIREBASE_PROJECT_ID: ${{secrets.PROD_FIREBASE_PROJECT_ID}}
  VITE_FIREBASE_STORAGE_BUCKET: ${{secrets.PROD_FIREBASE_STORAGE_BUCKET}}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.PROD_FIREBASE_MESSAGING_SENDER_ID}}
  VITE_FIREBASE_APP_ID: ${{secrets.PROD_FIREBASE_APP_ID}}
  VITE_BACKEND_BASE_URL: ${{secrets.PROD_BACKEND_BASE_URL}}
  VITE_ENV_STRIPE_PUBLISHABLE_KEY: ${{secrets.PROD_STRIPE_PK}}
  VITE_ENV: production

jobs:
  Deploy-Client:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3

      - name: Enable corepack
        run: corepack enable

      - name: Create env file
        run: echo ${{ secrets.UASC_DEV_FRONTEND_ENVFILE }} | base64 --decode > .env

      - run: sudo yarn workspaces focus client
      - run: CI=false sudo yarn build

      - uses: "google-github-actions/auth@v2"
        with:
          # Credentials stored inside WDCC organisation secrets
          credentials_json: "${{ secrets.UASC_DEV_GCP_DEPLOYMENT_SA_CREDENTIALS }}"

      - uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          # Build path (path is excluded if parent: false flag)
          path: "client/build"
          parent: false

          # Buckets to add contents into
          destination: "uasc-dev.wdcc.co.nz"
