name: Deploy DEV

on: [workflow_dispatch]

jobs:
  Deploy-Client:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3

      - name: Enable corepack
        run: corepack enable

      - name: Create env file
        run: echo ${{ secrets.UASC_DEV_FRONTEND_ENVFILE }} | base64 --decode > .env

      - run: sudo yarn workspaces focus client
      - run: CI=false sudo yarn build

      - uses: "google-github-actions/auth@v2"
        with:
          # Credentials stored inside WDCC organisation secrets
          credentials_json: "${{ secrets.UASC_DEV_GCP_DEPLOYMENT_SA_CREDENTIALS }}"

      - uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          # Build path (path is excluded if parent: false flag)
          path: "client/build"
          parent: false

          # Buckets to add contents into
          destination: "uasc-dev.wdcc.co.nz"
