name: Deploy the Stable Build of Client for UASC

on:
  workflow_dispatch:
  # schedules this to run every day, at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

jobs:
  Deploy-Stable:
    runs-on: ubuntu-latest
    environment: Client Production

    steps:
      - run: gh workflow run 'Deploy Production Build of Client for UASC' --ref stable
