name: Fly Deploy Production

on: [workflow_dispatch]

jobs:
  # deploy-web:
  #   name: Deploy Web
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - run: flyctl deploy --remote-only --config fly.production.toml
  #       working-directory: ./web
  #       env:
  #         FLY_API_TOKEN: ${{ secrets.FLY_WEB_PRODUCTION_API_TOKEN }}

  deploy-api:
    name: Deploy Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.production.toml --env "GOOGLE_SERVICE_ACCOUNT_JSON=$(echo ${{ secrets.PROD_SERVER_SERVICE_ACCOUNT }} | base64 --decode) STRIPE_API_SECRET=${{ secrets.PROD_SERVER_STRIPE_API_SECRET }} STRIPE_API_KEY=${{ secrets.PROD_SERVER_STRIPE_API_KEY }}" 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_PRODUCTION_API_TOKEN }}
