name: "Lint"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Install NPM dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint
