name: "Lint and Test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Install NPM dependencies
        run: sudo yarn

      - name: Run ESLint on ALL files
        run: yarn lint-all

      - name: Run ALL unit tests
        run: yarn test
