name: Prettier
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable corepack
        run: corepack enable

      - run: sudo yarn
      - run: yarn prettier:ci
