name: Prettier
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install volta
        uses: volta-cli/action@v4

      - run: yarn
      - run: yarn prettier:ci
