name: Run all tests
on:
  pull_request:
  push:
    branches:
      - master

env:
  API_KEY: ${{secrets.VITE_FIREBASE_API_KEY}}

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable corepack
        run: corepack enable

      - run: sudo npm install -g firebase-tools
      - run: sudo yarn
      - run: yarn test
